name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2021-04-22
        override: true
        components: rustfmt, clippy
    - uses: actions/checkout@v2
    - name: TensorBase Release Build
      run: cargo build --release
    - name: TensorBase Prepare data dirs
      run: mkdir ${{ github.workspace }}/tb_data
    - name: TensorBase Run server
      run: |
           cargo run --bin server -- -s "$BASE_CONF" > out & 
      env:
          BASE_CONF: |
            [system]                  
            meta_dirs = ["${{ github.workspace }}/tb_schema"] 
            data_dirs = ["${{ github.workspace }}/tb_data"]   
            [storage]                          
            data_dirs_clickhouse = ""          
            [server]                           
            ip_addr = "localhost"              
            port = 9528   
     
    
