name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build
    - name: Run server
      run: |
           cargo run --bin server -s \
           '[system]                   \
            meta_dirs = ["/jin/tmp/tb_schema"] \
            data_dirs = ["/jin/tmp/tb_data"]   \
            [storage]                          \
            data_dirs_clickhouse = ""          \
            [server]                           \
            ip_addr = "localhost"              \
            port = 9528                        \
            ' &
    - name: Done
      run: echo "done"
     
    
